thread:
  threadPoolExecutor:
    corePoolSize: 10
    maximumPoolSize: 5
spring:
  #redis配置
  redis:
    password:  #密码（默认为空）
    timeout: 6000ms #链接超时时常（毫秒）
    cluster:
      nodes:
        - localhost:6380
        - localhost:6381
        - localhost:6382
        - localhost:6383
        - localhost:6384
        - localhost:6385
    jedis:
      pool:
        max-active: 1000 #连接池最大链接数（使用负值表示无限制）
        max-wait: -1ms #连接池最大阻塞等待时间（使用负值表示无限制）
        max-idle: 10 #连接池中最大空闲连接
        min-idle: 5 #连接池中最小空闲连接
